#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MboutiqueVisualElement.Droid.Resource", IsApplication=true)]

namespace MboutiqueVisualElement.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::MboutiqueVisualElement.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::MboutiqueVisualElement.Droid.Resource.String.Hello;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.error = global::MboutiqueVisualElement.Droid.Resource.Drawable.error;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.info = global::MboutiqueVisualElement.Droid.Resource.Drawable.info;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.success = global::MboutiqueVisualElement.Droid.Resource.Drawable.success;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.warning = global::MboutiqueVisualElement.Droid.Resource.Drawable.warning;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.desc = global::MboutiqueVisualElement.Droid.Resource.Id.desc;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.image = global::MboutiqueVisualElement.Droid.Resource.Id.image;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.title = global::MboutiqueVisualElement.Droid.Resource.Id.title;
			global::Toasts.Forms.Plugin.Droid.Resource.Layout.crouton = global::MboutiqueVisualElement.Droid.Resource.Layout.crouton;
			global::Toasts.Forms.Plugin.Droid.Resource.String.ApplicationName = global::MboutiqueVisualElement.Droid.Resource.String.ApplicationName;
			global::Toasts.Forms.Plugin.Droid.Resource.String.Hello = global::MboutiqueVisualElement.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::MboutiqueVisualElement.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::MboutiqueVisualElement.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int credit = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int credit_card = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int drawer = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int dustbin = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int error = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int facebook = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int hdback = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ico = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int info = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int logo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int mac = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int mBoutique = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int r1 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int r2 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int r3 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int r4 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int r5 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int softtrends = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int splash = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int star_outline = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int success = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int warning = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int desc = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int image = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int launchImage = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int title = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int crouton = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
